# Generated by Django 5.2 on 2025-04-16 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='assigned_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurses', to='myapp.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='myapp.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nurses',
            field=models.ManyToManyField(blank=True, related_name='patients', to='myapp.nurse'),
        ),
    ]
