# Generated by Django 5.2 on 2025-04-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_nurse_assigned_doc_alter_patient_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
