# Generated by Django 5.2 on 2025-04-24 16:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_prescription_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Appointments',
            field=models.ManyToManyField(blank=True, related_name='patients', to='myapp.prescription'),
        ),
        migrations.AddField(
            model_name='patient',
            name='admitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='myapp.staff'),
        ),
        migrations.AddField(
            model_name='patient',
            name='admitted_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='patient',
            name='discharged_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='Admitted', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
