# Generated by Django 5.2 on 2025-04-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_department_alter_doctor_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
