# Generated by Django 5.2 on 2025-04-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_staff_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='occupied',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
