# Generated by Django 5.2 on 2025-04-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('F', 'female'), ('M', 'Male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='gender',
            field=models.CharField(choices=[('F', 'female'), ('M', 'Male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'female'), ('M', 'Male')], max_length=10, null=True),
        ),
    ]
